### ISSUE TITLE
Messages are not being received by client

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-webserver#5]

**Comment by jmaldonadof** [comment]
This issue was resolved after the application of the fixes listed below:

- The AlarmDemultiplexer needs the group of clients that must be notified when the alarms are created, updated or deleted. The list of groups can be defined as a variable or with a function connection_groups to return the list of groups. After doing this change, the notifications are received by the web clients only if the alarms are created through the django admin panel but not if the change is made through Django shell.

- We noticed that we were using an inMemory backend for the channels layout, that allows the execution of the application using a single thread. We try to execute the application using a redis backend. The fix was not enough and the problem persisted. 

- We noticed that when we use the Django shell, only the classes that we import explicitly are executed. So, when we created the alarm, we were importing the AlarmFactory class, and the Alarm class, but we weren't importing the AlarmBinding class. Because of that, in the Django shell the binding is unknown. To fix that and to avoid future problems, we moved the AlarmBinding to the models.py file, just below of Alarm model description.

- With those changes the problem was fixed. We also verified that the redis backend is necessary because after the application of the last change we try to run the server using the InMemory backend again and the problem came back.
